### ISSUE TITLE
Error in/Fehler in BMx280MI::getPressure64() v1.1

### ISSUE THREAD

**Issue by hHoch3** [christandlg/BMx280MI#1]
Hallo there is an (or two) error(s) in BMx280MI::getPressure64() in Line 193 in BMx280MI.cpp in V1.1:

original: 
p = (p + var1 + var2) >> 8 + (static_cast<int64_t>(comp_params_.dig_P8_) << 4);
Missing Bracket:  Ist makes a  comp_params_.dig_P8_ right shift*16 right shift 
comp_params_.dig_P8_ is negative so ist does nothing
The correct var comp_params_.dig_P8_ (from the Bosch example) is posive. So p is 0 without the brackets

correct:
p = ((p + var1 + var2) >> 8) + (static_cast<int64_t>(comp_params_.dig_P7_) << 4);

Deutsch:
Hallo, es gibt einen (bzw zwei) Fehler in BMx280MI::getPressure64() in Linie 193 in BMx280MI.cpp in V1.1:

Original: 
p = (p + var1 + var2) >> 8 + (static_cast<int64_t>(comp_params_.dig_P8_) << 4);
Fehlende Klammern: Es mach einen 16fachen comp_params_.dig_P8_ right shifit.
Da comp_params_.dig_P8_ negativ ist Passiert nichts. (Abweichende werte nur.)
Die korrekte Variable comp_params_.dig_P8_ (aus dem Bosch Beispiel) ist posiv. 
Daher is P =0 ohne die Klammern

Richtig:
p = ((p + var1 + var2) >> 8) + (static_cast<int64_t>(comp_params_.dig_P7_) << 4);

Grüße Holger

**Comment by christandlg** [comment]
fixed in bbcbe506bbb93cbc40bd5b9aaec7110c47cb2373
